webservice:
  prefix: "api"
  address: "127.0.0.1:8080"
  forwarding_headers: []

persistence:
  db:
    pool_size: 10
    automigrate: true
    acquire_timeout: 30
    connection:
      url: "postgres://localhost:5432/service_capture"
      username: "user"
      password: "password"
