apiVersion: v2
name: service-capture-backend
description: Backend for Service Capture. Provides the API for capturing services and storing them in a database.
version: 0.1.0
appVersion: 0.2.0
dependencies: []
