apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: service-capture
resources:
  - app-service-capture.yaml
  - repository.yaml
  - keycloak-realm.yaml
  - telemetry-logs.yaml
  - test-users.yaml
