---
hams:
  address: 0.0.0.0:8079
  prefix: hams
  logging: true
  checks:
    timeout: 5
    fails: 2
    preflights: []
    # - http://localhost:4201
    shutdowns: []
runtime:
  stack_size: 3145728
  threads: 4
  name: service-capture
webservice:
  prefix: /capture
  address: 0.0.0.0:8080
  forwarding_headers: []
persistence:
  db:
    pool_size: 20
    automigrate: true
    acquire_timeout: 3
    connection:
      url: postgres://localhost:5432/service-capture
      username_file: db/username
      password_file: db/password
