---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "service-capture-backend.fullname" . }}
  labels:
    {{- include "service-capture-backend.labels" . | nindent 4 }}
data:
  serviceconfig.yaml: |
    {{- include "service-capture-backend.config" . | nindent 4 }}
