{{- if .Values.devsecops.AuthorizationPolicy.rules  -}}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "nginx-view.fullname" . }}
  labels:
    {{- include "nginx-view.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "nginx-view.selectorLabels" . | nindent 6 }}
  action: ALLOW
  rules:
  {{-  tpl (toYaml .Values.devsecops.AuthorizationPolicy.rules) . | nindent 4 }}
{{- end -}}
