---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-view.fullname" . }}-inits
  labels:
    {{- include "nginx-view.labels" . | nindent 4 }}
data:
  {{-  (include "nginx-view.getInits" .) | nindent 2 }}
